#!/usr/bin/python
import os
import time
import sqlite3
import sys

def readTemp():
        tempfile = open("/sys/bus/w1/devices/---/w1_slave")
        tempfile_text=tempfile.read()
        currentTime=time.strftime('%x %X %Z')
        tempfile.close()
        tempC=float(tempfile_text.split("\n")[1].split("t=")[1])/1000
        tempF=tempC*9.0/5.0+32.0
        return [currentTime, tempC, tempF]

def logTemp():
        con = TempLog.connect()
        cur=con.cursor()
        cur.execute("CREATE TABLE TempData(Time timestamp, Celsius C, Fahrenhei$
        [t,C,F]=readTemp()
        cur.execute('INSERT INTO TempData values(?,?,?)',(t,C,F)

logTemp()
#Couldn't get Temp Sensor to work
