#!/usr/bin/python
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)

def Blink():
        r = 1
        k = 1
        while(r == 1):
         for i in range(0,3):
                print "blink alpha #" + str(i+1)
                GPIO.output(17,True)
                time.sleep(0.5)
                GPIO.output(17,False)
                time.sleep(0.5)

         time.sleep(5)

         for i in range(0,4):
                print "blink beta #" + str(i+1)
                GPIO.output(17,True)
                time.sleep(0.5)
                GPIO.output(17,False)
                time.sleep(0.5)
         print "Complete Set#" + str(k)
         k=k+1
         time.sleep(5)
        GPIO.cleanup()
Blink()
